# .travis.ylm
# Modified travis script that generates and submits doxygen documentation
sudo: false
language: cpp
branches:
    except:
        - gh-pages
# Modify these variables that will be used in generateDocumentationAndDeploy.sh
# (see below). They tell Doxygen where to find the source on and where to send
# the generated documentation.
env:
  global:
    - GH_REPO_NAME: H62PEP-week1
    - DOXYFILE: "$TRAVIS_BUILD_DIR/QtModelLoader/Doxyfile"
    - GH_REPO_REF: github.com/eeyaw4/Group20ProjectWork
# The virtual machines created by Travis do not by default have doxygen
# installed. This is fortunately not difficult on a Debian flavoured Linux
# system.

before_install:
    - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
    - sudo apt-get -qq update

install:
    - sudo apt-get --yes install qt55base qt55imageformats qt55svg

addons:
    apt:
        packages:
            - doxygen
            - graphviz

before_script:
    - QTDIR="/opt/qt55"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt55/bin/qt55-env.sh
script:
    - make
# After successfully building and testing your software we give Doxygen the
# instruction to scan the code for docstrings and generate the html output.
# The bulk of these instructions is encapsulated in a script.
after_success:
    - cd $TRAVIS_BUILD_DIR
    - chmod +x generateDocumentationAndDeploy.sh
    - ./generateDocumentationAndDeploy.sh